package:
  name: proj4
  version: 4.7.0

source:
  fn: proj-4.7.0.tar.gz
  url: http://download.osgeo.org/proj/proj-4.7.0.tar.gz
#  md5: 
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - paste = paste:main
    #
    # Would create an entry point called paste that calls paste.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

#requirements:
#  build:
#    - python
#    - distribute

about:
  home: http://trac.osgeo.org/proj
  license: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
