package:
  name: pycrypto
  version: 2.6

source:
  fn: pycrypto-2.6.tar.gz
  url: https://pypi.python.org/packages/source/p/pycrypto/pycrypto-2.6.tar.gz
  md5: 88dad0a270d1fe83a39e0467a66a22bb
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pycrypto = pycrypto:main
    #
    # Would create an entry point called pycrypto that calls pycrypto.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - Crypto

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.pycrypto.org/
  license: UNKNOWN

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
