package:
  name: gitdb
  version: 0.5.4

source:
  fn: gitdb-0.5.4.tar.gz
  url: https://pypi.python.org/packages/source/g/gitdb/gitdb-0.5.4.tar.gz
  md5: 25353bb8d3ea527ba443dd88cd4e8a1c
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - gitdb = gitdb:main
    #
    # Would create an entry point called gitdb that calls gitdb.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - async
    - smmap

  run:
    - python
    - async
    - smmap

test:
  # Python imports
  imports:
    - gitdb

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/gitpython-developers/gitdb
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
