package:
  name: pyyaml
  version: 3.10

source:
  fn: PyYAML-3.10.tar.gz
  url: https://pypi.python.org/packages/source/P/PyYAML/PyYAML-3.10.tar.gz
  md5: 74c94a383886519e9e7b3dd1ee540247
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyyaml = pyyaml:main
    #
    # Would create an entry point called pyyaml that calls pyyaml.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - yaml

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pyyaml.org/wiki/PyYAML
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
