package:
  name: django
  version: 1.2.3

source:
  fn: Django-1.2.3.tar.gz
  url: https://pypi.python.org/packages/source/D/Django/Django-1.2.3.tar.gz
  md5: 10bfb5831bcb4d3b1e6298d0e41d6603
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - django = django:main
    #
    # Would create an entry point called django that calls django.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - django

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.djangoproject.com/
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
