package:
  name: sqlalchemy
  version: 0.6.5

source:
  fn: SQLAlchemy-0.6.5.tar.gz
  url: https://pypi.python.org/packages/source/S/SQLAlchemy/SQLAlchemy-0.6.5.tar.gz
  md5: a64f3d3115285d50ec52349e5e8e0214
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sqlalchemy = sqlalchemy:main
    #
    # Would create an entry point called sqlalchemy that calls sqlalchemy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python

test:
  # Python imports
  imports:
    - sqlalchemy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.sqlalchemy.org
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
