package:
  name: gitpython
  version: 0.3.2.RC1

source:
  fn: GitPython-0.3.2.RC1.tar.gz
  url: https://pypi.python.org/packages/source/G/GitPython/GitPython-0.3.2.RC1.tar.gz
  md5: 849082fe29adc653a3621465213cab96
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - gitpython = gitpython:main
    #
    # Would create an entry point called gitpython that calls gitpython.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute
    - gitdb
    
  run:
    - python
    - gitdb
    
test:
  # Python imports
  imports:
    - git

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://gitorious.org/projects/git-python/
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
