package:
  name: salt
  version: 0.17.0

source:
  fn: salt-0.17.0.tar.gz
  url: https://pypi.python.org/packages/source/s/salt/salt-0.17.0.tar.gz
  md5: c51dc289d7d7c49e6ebd74519f116441
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - salt = salt:main
    #
    # Would create an entry point called salt that calls salt.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - jinja2
    - m2crypto
    - msgpack-python
    - pycrypto
    - pyyaml
    - pyzmq
    - zeromq 3.2.*

  run:
    - python
    - jinja2
    - m2crypto
    - msgpack-python
    - pycrypto
    - pyyaml
    - pyzmq 
    - zeromq 3.2.*

test:
  # Python imports
  imports:
    - salt

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://saltstack.org
  license: Apache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
